### ISSUE TITLE
Readonly DB

### ISSUE THREAD

**Issue by tomsaleeba** [ternandsparrow/wild-orchid-watch-api-facade#19]
Saw this error on dev:

```
2022-08-14T01:00:59.807Z [ERROR] Error while running function obsUpsertHandler SqliteError: attempt to write a readonly database
at insertUploadRecord (/home/node/app/src/data-producers.js:690:4)
at /home/node/app/src/data-producers.js:164:22
at sqliteTransaction (/home/node/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
at obsUpsertHandler (/home/node/app/src/data-producers.js:185:3) {
code: 'SQLITE_READONLY_DBMOVED'
```

Was running pwa locally, testing indexeddb migration code. Didn't touch anything, just tried again ~20 mins later and it worked.

**Comment by tomsaleeba** [comment]
Idea: check if we've using litestream to sync DB to GCS or if we're just pointing to the mounted volume. If the latter, maybe we can switch the former. Although if the GCS volume is read-only, writes are still going to fail anyway, this is just a canary.

**Comment by tomsaleeba** [comment]
It happened again with a tiny DB, so I've done the swap to litestream and we'll see how that goes.

**Comment by tomsaleeba** [comment]
Seems to be fixed for now :crossed_fingers:
